In [1]:
import tensorflow as tf
import keras

C:\Users\LGB\Anaconda3\envs\lgb_01\lib\site-packages\tensorflow\python\framework\dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\LGB\Anaconda3\envs\lgb_01\lib\site-packages\tensorflow\python\framework\dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\LGB\Anaconda3\envs\lgb_01\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\LGB\Anaconda3\envs\lgb_01\lib\site-packages\tensorflow\python\frame

In [2]:
tf.__version__

'1.12.0'

In [3]:
keras.__version__

'2.2.4'

In [4]:
raw_text = '''张无忌，金庸武侠小说《倚天屠龙记》人物角色，中土明教第三十四代教主。武当七侠之一张翠山与天鹰教紫微堂主殷素素之子，明教四大护教法王之一金毛狮王谢逊义子。
              张翠山，《倚天屠龙记》第一卷的男主角，在武当七侠之中排行第五，人称张五侠。与天鹰教殷素素结为夫妇，生下张无忌，后流落到北极冰海上的冰火岛，与谢逊相识并结为兄弟。
              殷素素，金庸武侠小说《倚天屠龙记》第一卷的女主人公。天鹰教紫薇堂堂主，容貌娇艳无伦，智计百出，亦正亦邪。与武当五侠张翠山同赴王盘山，结果被金毛狮王谢逊强行带走，三人辗转抵达冰火岛。殷素素与张翠山在岛上结为夫妇，并诞下一子张无忌。
              谢逊，是金庸武侠小说《倚天屠龙记》中的人物，字退思，在明教四大护教法王中排行第三，因其满头金发，故绰号“金毛狮王”。
           '''
annotations = {'name':['张无忌','张翠山','殷素素','谢逊'], 'book':['倚天屠龙记'],'org':['明教','武当','天鹰教']}
raw_text, annotations

('张无忌，金庸武侠小说《倚天屠龙记》人物角色，中土明教第三十四代教主。武当七侠之一张翠山与天鹰教紫微堂主殷素素之子，明教四大护教法王之一金毛狮王谢逊义子。\n              张翠山，《倚天屠龙记》第一卷的男主角，在武当七侠之中排行第五，人称张五侠。与天鹰教殷素素结为夫妇，生下张无忌，后流落到北极冰海上的冰火岛，与谢逊相识并结为兄弟。\n              殷素素，金庸武侠小说《倚天屠龙记》第一卷的女主人公。天鹰教紫薇堂堂主，容貌娇艳无伦，智计百出，亦正亦邪。与武当五侠张翠山同赴王盘山，结果被金毛狮王谢逊强行带走，三人辗转抵达冰火岛。殷素素与张翠山在岛上结为夫妇，并诞下一子张无忌。\n              谢逊，是金庸武侠小说《倚天屠龙记》中的人物，字退思，在明教四大护教法王中排行第三，因其满头金发，故绰号“金毛狮王”。\n           ',
 {'name': ['张无忌', '张翠山', '殷素素', '谢逊'],
  'book': ['倚天屠龙记'],
  'org': ['明教', '武当', '天鹰教']})

In [5]:
import re

# 先去掉原始文本中的换行和空格符
raw_text = raw_text.replace('\n', '').replace(' ', '')
# 初始化 label：将其全部初始化为 O
labels = len(raw_text)*['O']

# 通过 key-value 的方式遍历 annotations 字典，进行转换
for ann, entities in annotations.items():
    for entity in entities:
        # 先生成实体对应的 BME 标注类型
        B, M, E = [['{}_{}'.format(ann,i)] for i in ['B','M','E']]
        # 计算实体词中的数量
        M_len = len(entity) - 2
        # 生成 label，如果词中数为0，则直接为 BE，不然按数量添加 M
        label = B + M * M_len + E if M_len else B + E
        # 从原始文本中找到实体对应出现的所有位置
        idxs = [r.start() for r in re.finditer(entity, raw_text)]

        for idx in idxs:
        # 替换原 label 中的 O 为实际 label
            labels[idx:idx+len(entity)] = label


# 打印原始文本和对应转换后的 label
for ann,label in zip(raw_text,labels):
    print(ann, label)

张 name_B
无 name_M
忌 name_E
， O
金 O
庸 O
武 O
侠 O
小 O
说 O
《 O
倚 book_B
天 book_M
屠 book_M
龙 book_M
记 book_E
》 O
人 O
物 O
角 O
色 O
， O
中 O
土 O
明 org_B
教 org_E
第 O
三 O
十 O
四 O
代 O
教 O
主 O
。 O
武 org_B
当 org_E
七 O
侠 O
之 O
一 O
张 name_B
翠 name_M
山 name_E
与 O
天 org_B
鹰 org_M
教 org_E
紫 O
微 O
堂 O
主 O
殷 name_B
素 name_M
素 name_E
之 O
子 O
， O
明 org_B
教 org_E
四 O
大 O
护 O
教 O
法 O
王 O
之 O
一 O
金 O
毛 O
狮 O
王 O
谢 name_B
逊 name_E
义 O
子 O
。 O
张 name_B
翠 name_M
山 name_E
， O
《 O
倚 book_B
天 book_M
屠 book_M
龙 book_M
记 book_E
》 O
第 O
一 O
卷 O
的 O
男 O
主 O
角 O
， O
在 O
武 org_B
当 org_E
七 O
侠 O
之 O
中 O
排 O
行 O
第 O
五 O
， O
人 O
称 O
张 O
五 O
侠 O
。 O
与 O
天 org_B
鹰 org_M
教 org_E
殷 name_B
素 name_M
素 name_E
结 O
为 O
夫 O
妇 O
， O
生 O
下 O
张 name_B
无 name_M
忌 name_E
， O
后 O
流 O
落 O
到 O
北 O
极 O
冰 O
海 O
上 O
的 O
冰 O
火 O
岛 O
， O
与 O
谢 name_B
逊 name_E
相 O
识 O
并 O
结 O
为 O
兄 O
弟 O
。 O
殷 name_B
素 name_M
素 name_E
， O
金 O
庸 O
武 O
侠 O
小 O
说 O
《 O
倚 book_B
天 book_M
屠 book_M
龙 book_M
记 book_E
》 O
第 O
一 O
卷 O
的 O
女 O
主 O
人 O
公 O
。 O
天 org_B
鹰 org_M


In [6]:
from collections import Counter
import numpy as np
from keras.preprocessing.sequence import pad_sequences

In [8]:
# 统计每个字出现的次数
word_counts = Counter(raw_text)
# 建立字典表，只记录出现次数不小于 2 的字
vocab = [w for w, f in iter(word_counts.items()) if f >= 2]
word_counts

Counter({'张': 8,
         '无': 4,
         '忌': 3,
         '，': 21,
         '金': 7,
         '庸': 3,
         '武': 6,
         '侠': 7,
         '小': 3,
         '说': 3,
         '《': 4,
         '倚': 4,
         '天': 7,
         '屠': 4,
         '龙': 4,
         '记': 4,
         '》': 4,
         '人': 5,
         '物': 2,
         '角': 2,
         '色': 1,
         '中': 4,
         '土': 1,
         '明': 3,
         '教': 9,
         '第': 5,
         '三': 3,
         '十': 1,
         '四': 3,
         '代': 1,
         '主': 5,
         '。': 9,
         '当': 3,
         '七': 2,
         '之': 4,
         '一': 5,
         '翠': 4,
         '山': 5,
         '与': 5,
         '鹰': 3,
         '紫': 2,
         '微': 1,
         '堂': 3,
         '殷': 4,
         '素': 8,
         '子': 3,
         '大': 2,
         '护': 2,
         '法': 2,
         '王': 6,
         '毛': 3,
         '狮': 3,
         '谢': 4,
         '逊': 4,
         '义': 1,
         '卷': 2,
         '的': 4,
         '男': 1,
         '在':

In [9]:
vocab

['张',
 '无',
 '忌',
 '，',
 '金',
 '庸',
 '武',
 '侠',
 '小',
 '说',
 '《',
 '倚',
 '天',
 '屠',
 '龙',
 '记',
 '》',
 '人',
 '物',
 '角',
 '中',
 '明',
 '教',
 '第',
 '三',
 '四',
 '主',
 '。',
 '当',
 '七',
 '之',
 '一',
 '翠',
 '山',
 '与',
 '鹰',
 '紫',
 '堂',
 '殷',
 '素',
 '子',
 '大',
 '护',
 '法',
 '王',
 '毛',
 '狮',
 '谢',
 '逊',
 '卷',
 '的',
 '在',
 '排',
 '行',
 '五',
 '结',
 '为',
 '夫',
 '妇',
 '下',
 '冰',
 '上',
 '火',
 '岛',
 '并',
 '亦']

In [10]:
label_set = list(set(labels))

# 拆分训练集，每一句话作为一个样本，先找到每个句号的位置
sentence_len = [r.start()+1 for r in re.finditer('。', raw_text)]

# 进行拆分，这里要注意最后一个句号后面不需要拆分，所以最后一个位置不需要取到
split_text = np.split(list(raw_text), sentence_len[:-1])
split_label = np.split(labels, sentence_len[:-1])
split_text, split_label

([array(['张', '无', '忌', '，', '金', '庸', '武', '侠', '小', '说', '《', '倚', '天',
         '屠', '龙', '记', '》', '人', '物', '角', '色', '，', '中', '土', '明', '教',
         '第', '三', '十', '四', '代', '教', '主', '。'], dtype='<U1'),
  array(['武', '当', '七', '侠', '之', '一', '张', '翠', '山', '与', '天', '鹰', '教',
         '紫', '微', '堂', '主', '殷', '素', '素', '之', '子', '，', '明', '教', '四',
         '大', '护', '教', '法', '王', '之', '一', '金', '毛', '狮', '王', '谢', '逊',
         '义', '子', '。'], dtype='<U1'),
  array(['张', '翠', '山', '，', '《', '倚', '天', '屠', '龙', '记', '》', '第', '一',
         '卷', '的', '男', '主', '角', '，', '在', '武', '当', '七', '侠', '之', '中',
         '排', '行', '第', '五', '，', '人', '称', '张', '五', '侠', '。'], dtype='<U1'),
  array(['与', '天', '鹰', '教', '殷', '素', '素', '结', '为', '夫', '妇', '，', '生',
         '下', '张', '无', '忌', '，', '后', '流', '落', '到', '北', '极', '冰', '海',
         '上', '的', '冰', '火', '岛', '，', '与', '谢', '逊', '相', '识', '并', '结',
         '为', '兄', '弟', '。'], dtype='<U1'),
  array(['殷', '素', '素', '，', '金', 

In [11]:
# 构建词袋模型，这里要将字典从 2 开始编号，把 0 和 1 空出来，0 作为填充元素，1 作为不在字典中的字的编号
word2idx = dict((w,i+2) for i,w in enumerate(vocab))
label2idx = [[label_set.index(w) for w in s] for s in split_label]
word2idx, label2idx

({'张': 2,
  '无': 3,
  '忌': 4,
  '，': 5,
  '金': 6,
  '庸': 7,
  '武': 8,
  '侠': 9,
  '小': 10,
  '说': 11,
  '《': 12,
  '倚': 13,
  '天': 14,
  '屠': 15,
  '龙': 16,
  '记': 17,
  '》': 18,
  '人': 19,
  '物': 20,
  '角': 21,
  '中': 22,
  '明': 23,
  '教': 24,
  '第': 25,
  '三': 26,
  '四': 27,
  '主': 28,
  '。': 29,
  '当': 30,
  '七': 31,
  '之': 32,
  '一': 33,
  '翠': 34,
  '山': 35,
  '与': 36,
  '鹰': 37,
  '紫': 38,
  '堂': 39,
  '殷': 40,
  '素': 41,
  '子': 42,
  '大': 43,
  '护': 44,
  '法': 45,
  '王': 46,
  '毛': 47,
  '狮': 48,
  '谢': 49,
  '逊': 50,
  '卷': 51,
  '的': 52,
  '在': 53,
  '排': 54,
  '行': 55,
  '五': 56,
  '结': 57,
  '为': 58,
  '夫': 59,
  '妇': 60,
  '下': 61,
  '冰': 62,
  '上': 63,
  '火': 64,
  '岛': 65,
  '并': 66,
  '亦': 67},
 [[9,
   3,
   0,
   4,
   4,
   4,
   4,
   4,
   4,
   4,
   4,
   7,
   1,
   1,
   1,
   8,
   4,
   4,
   4,
   4,
   4,
   4,
   4,
   4,
   2,
   5,
   4,
   4,
   4,
   4,
   4,
   4,
   4,
   4],
  [2,
   5,
   4,
   4,
   4,
   4,
   9,
   3,
   0,
   4,
   2,
   6,
   5

In [12]:
# 构建输入，即对于样本中每一个字，从词袋模型中找到这个字对应的 idx，出现频率过低的字，并没有出现在词袋模型中，此时将这些字的 idx 取为 1
train_x = [[word2idx.get(w, 1) for w in s] for s in split_text]

max_len = 64

# 在输入的左边填充 0，在输出的左端填充-1
train_x = pad_sequences(train_x, max_len, value=0)
train_y = pad_sequences(label2idx, max_len, value=-1)
train_y = np.expand_dims(train_y, 2)
train_x.shape, train_y.shape

((9, 64), (9, 64, 1))

In [14]:
from keras.models import Sequential
from keras.layers import Embedding, Bidirectional, LSTM
from keras_contrib.layers import CRF
from keras_contrib.losses import crf_loss

In [15]:
# 定义模型的超参
EMBED_DIM = 200
BiRNN_UNITS = 200

# 初始化模型
model = Sequential()
# 添加 Embedding 层，将输入转换成向量
model.add(Embedding(len(vocab)+2, EMBED_DIM, mask_zero=True))
# 添加 BiLstm 层
model.add(Bidirectional(LSTM(BiRNN_UNITS // 2, return_sequences=True)))
# 初始化 crf
crf = CRF(len(train_y), sparse_target=True)
# 将 crf 添加到模型中
model.add(crf)
model.summary()
# 编译模型
model.compile('adam', loss=crf_loss, metrics=[crf.accuracy])

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, None, 200)         13600     
_________________________________________________________________
bidirectional_1 (Bidirection (None, None, 200)         240800    
_________________________________________________________________
crf_1 (CRF)                  (None, None, 9)           1908      
Total params: 256,308
Trainable params: 256,308
Non-trainable params: 0
_________________________________________________________________


C:\Users\LGB\Anaconda3\envs\lgb_01\lib\site-packages\keras_contrib\layers\crf.py:353: UserWarning: CRF.accuracy is deprecated and it might be removed in the future. Please use metrics.crf_accuracy
  warnings.warn('CRF.accuracy is deprecated and it '


In [16]:
model.fit(train_x, train_y, batch_size=9, epochs=120)
model.save('model.h5')

Epoch 1/120
9/9 [==============================] - 2s 268ms/step - loss: 4.1894 - crf_viterbi_accuracy: 0.0457
Epoch 2/120
9/9 [==============================] - 0s 11ms/step - loss: 4.1527 - crf_viterbi_accuracy: 0.0457
Epoch 3/120
9/9 [==============================] - 0s 9ms/step - loss: 4.1145 - crf_viterbi_accuracy: 0.0457
Epoch 4/120
9/9 [==============================] - 0s 10ms/step - loss: 4.0722 - crf_viterbi_accuracy: 0.0457
Epoch 5/120
9/9 [==============================] - 0s 11ms/step - loss: 4.0230 - crf_viterbi_accuracy: 0.0457
Epoch 6/120
9/9 [==============================] - 0s 11ms/step - loss: 3.9634 - crf_viterbi_accuracy: 0.0457
Epoch 7/120
9/9 [==============================] - 0s 10ms/step - loss: 3.8897 - crf_viterbi_accuracy: 0.0793
Epoch 8/120
9/9 [==============================] - 0s 11ms/step - loss: 3.7968 - crf_viterbi_accuracy: 0.2256
Epoch 9/120
9/9 [==============================] - 0s 10ms/step - loss: 3.6784 - crf_viterbi_accuracy: 0.4451
Epoch 10/1

9/9 [==============================] - 0s 10ms/step - loss: 2.4350 - crf_viterbi_accuracy: 0.8232
Epoch 76/120
9/9 [==============================] - 0s 9ms/step - loss: 2.4230 - crf_viterbi_accuracy: 0.8232
Epoch 77/120
9/9 [==============================] - 0s 9ms/step - loss: 2.4111 - crf_viterbi_accuracy: 0.8262
Epoch 78/120
9/9 [==============================] - 0s 10ms/step - loss: 2.3992 - crf_viterbi_accuracy: 0.8293
Epoch 79/120
9/9 [==============================] - 0s 10ms/step - loss: 2.3871 - crf_viterbi_accuracy: 0.8293
Epoch 80/120
9/9 [==============================] - 0s 10ms/step - loss: 2.3749 - crf_viterbi_accuracy: 0.8323
Epoch 81/120
9/9 [==============================] - 0s 9ms/step - loss: 2.3627 - crf_viterbi_accuracy: 0.8354
Epoch 82/120
9/9 [==============================] - 0s 9ms/step - loss: 2.3503 - crf_viterbi_accuracy: 0.8384
Epoch 83/120
9/9 [==============================] - 0s 9ms/step - loss: 2.3379 - crf_viterbi_accuracy: 0.8415
Epoch 84/120
9/9 [=

In [17]:
text = '谢逊，是金庸武侠小说《倚天屠龙记》中的人物，字退思，在明教四大护教法王中排行第三，因其满头金发，故绰号“金毛狮王"。'
text

'谢逊，是金庸武侠小说《倚天屠龙记》中的人物，字退思，在明教四大护教法王中排行第三，因其满头金发，故绰号“金毛狮王"。'

In [18]:
# 将预测数据转换为特征向量
pred_x = [word2idx.get(w, 1) for w in text]
pred_x = pad_sequences([pred_x], max_len)
pred_x

array([[ 0,  0,  0,  0,  0,  0, 49, 50,  5,  1,  6,  7,  8,  9, 10, 11,
        12, 13, 14, 15, 16, 17, 18, 22, 52, 19, 20,  5,  1,  1,  1,  5,
        53, 23, 24, 27, 43, 44, 24, 45, 46, 22, 54, 55, 25, 26,  5,  1,
         1,  1,  1,  6,  1,  5,  1,  1,  1,  1,  6, 47, 48, 46,  1, 29]])

In [19]:
# 使用模型进行预测
pred = model.predict(pred_x)
pred.shape

(1, 64, 9)

In [20]:
# 去除多余的维度
pred = np.squeeze(pred)[-len(text):]
pred.shape

(58, 9)

In [21]:
# 把输出向量转换为 label 对应的 idx
result = [np.argmax(r) for r in pred]
result

[3,
 0,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 7,
 1,
 1,
 1,
 8,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 2,
 5,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4]

In [22]:
# 打印输出结果
reslut_labels = [label_set[i] for i in result]
for w, l in zip(text, reslut_labels):
    print(w, l)

谢 name_M
逊 name_E
， O
是 O
金 O
庸 O
武 O
侠 O
小 O
说 O
《 O
倚 book_B
天 book_M
屠 book_M
龙 book_M
记 book_E
》 O
中 O
的 O
人 O
物 O
， O
字 O
退 O
思 O
， O
在 O
明 org_B
教 org_E
四 O
大 O
护 O
教 O
法 O
王 O
中 O
排 O
行 O
第 O
三 O
， O
因 O
其 O
满 O
头 O
金 O
发 O
， O
故 O
绰 O
号 O
“ O
金 O
毛 O
狮 O
王 O
" O
。 O


In [23]:
# 对于 lists 中每一个子列表，第一个元素为实体1，第二个元素为实体2，第三个元素为实体1对实体2的关系，第四个元素为文本。
lists = [['杨康','杨铁心','子女','杨康，杨铁心与包惜弱之子，金国六王爷完颜洪烈的养子。'],
         ['杨康','杨铁心','子女','丘处机与杨铁心、郭啸天结识后，以勿忘“靖康之耻”替杨铁心的儿子杨康取名。'],
         ['杨铁心','包惜弱','配偶','金国六王爷完颜洪烈因为贪图杨铁心的妻子包惜弱的美色，杀害了郭靖的父亲郭啸天。'],
         ['杨铁心','包惜弱','配偶','杨康，杨铁心与包惜弱之子，金国六王爷完颜洪烈的养子。'],
         ['张翠山','殷素素','配偶','张无忌,武当七侠之一张翠山与天鹰教紫微堂主殷素素之子。'],
         ['小龙女','杨过','师傅','小龙女是杨过的师父，与杨过互生情愫，但因师生恋不容于世。'],
         ['黄药师','黄蓉','父','黄药师，黄蓉之父，对其妻冯氏（小字阿衡）一往情深。'],
         ['郭啸天','郭靖','父','郭靖之父郭啸天和其义弟杨铁心因被段天德陷害，死于临安牛家村。']]

relation2idx = {'子女':0,'配偶':1,'师傅':2,'父':3}

lists, relation2idx

([['杨康', '杨铁心', '子女', '杨康，杨铁心与包惜弱之子，金国六王爷完颜洪烈的养子。'],
  ['杨康', '杨铁心', '子女', '丘处机与杨铁心、郭啸天结识后，以勿忘“靖康之耻”替杨铁心的儿子杨康取名。'],
  ['杨铁心', '包惜弱', '配偶', '金国六王爷完颜洪烈因为贪图杨铁心的妻子包惜弱的美色，杀害了郭靖的父亲郭啸天。'],
  ['杨铁心', '包惜弱', '配偶', '杨康，杨铁心与包惜弱之子，金国六王爷完颜洪烈的养子。'],
  ['张翠山', '殷素素', '配偶', '张无忌,武当七侠之一张翠山与天鹰教紫微堂主殷素素之子。'],
  ['小龙女', '杨过', '师傅', '小龙女是杨过的师父，与杨过互生情愫，但因师生恋不容于世。'],
  ['黄药师', '黄蓉', '父', '黄药师，黄蓉之父，对其妻冯氏（小字阿衡）一往情深。'],
  ['郭啸天', '郭靖', '父', '郭靖之父郭啸天和其义弟杨铁心因被段天德陷害，死于临安牛家村。']],
 {'子女': 0, '配偶': 1, '师傅': 2, '父': 3})

In [24]:
datas, labels, pos_list1, pos_list2 = [], [], [], []
translation = 32
for entity1, entity2, relation, text in lists:
    # 找到第一个实体出现的下标
    idx1 = text.index(entity1)
    # 找到第二个实体出现的下标
    idx2 = text.index(entity2)
    sentence, pos1, pos2 = [], [], []
    for i, w in enumerate(text):
        sentence.append(w)
        # 计算句子中每个字与实体1首字的距离
        pos1.append(i-idx1+translation)
        # 计算句子中每个字与实体2首字的距离
        pos2.append(i-idx2+translation)
    datas.append(sentence)
    labels.append(relation2idx[relation])
    pos_list1.append(pos1)
    pos_list2.append(pos2)

datas, labels, pos_list1, pos_list2

([['杨',
   '康',
   '，',
   '杨',
   '铁',
   '心',
   '与',
   '包',
   '惜',
   '弱',
   '之',
   '子',
   '，',
   '金',
   '国',
   '六',
   '王',
   '爷',
   '完',
   '颜',
   '洪',
   '烈',
   '的',
   '养',
   '子',
   '。'],
  ['丘',
   '处',
   '机',
   '与',
   '杨',
   '铁',
   '心',
   '、',
   '郭',
   '啸',
   '天',
   '结',
   '识',
   '后',
   '，',
   '以',
   '勿',
   '忘',
   '“',
   '靖',
   '康',
   '之',
   '耻',
   '”',
   '替',
   '杨',
   '铁',
   '心',
   '的',
   '儿',
   '子',
   '杨',
   '康',
   '取',
   '名',
   '。'],
  ['金',
   '国',
   '六',
   '王',
   '爷',
   '完',
   '颜',
   '洪',
   '烈',
   '因',
   '为',
   '贪',
   '图',
   '杨',
   '铁',
   '心',
   '的',
   '妻',
   '子',
   '包',
   '惜',
   '弱',
   '的',
   '美',
   '色',
   '，',
   '杀',
   '害',
   '了',
   '郭',
   '靖',
   '的',
   '父',
   '亲',
   '郭',
   '啸',
   '天',
   '。'],
  ['杨',
   '康',
   '，',
   '杨',
   '铁',
   '心',
   '与',
   '包',
   '惜',
   '弱',
   '之',
   '子',
   '，',
   '金',
   '国',
   '六',
   '王',
   '爷',
   '完',
   '颜',
   '洪',
   '烈',
   '的',
   '养',
   '子

In [25]:
from collections import Counter
# 统计每个字出现的次数, sum(datas,[]) 的功能是将列表铺平
word_counts = Counter(sum(datas, []))
# 建立字典表，只记录出现次数不小于 2 的字
vocab = [w for w, f in iter(word_counts.items()) if f >= 2]
word_counts, vocab

(Counter({'杨': 11,
          '康': 4,
          '，': 11,
          '铁': 6,
          '心': 6,
          '与': 5,
          '包': 3,
          '惜': 3,
          '弱': 3,
          '之': 7,
          '子': 7,
          '金': 3,
          '国': 3,
          '六': 3,
          '王': 3,
          '爷': 3,
          '完': 3,
          '颜': 3,
          '洪': 3,
          '烈': 3,
          '的': 7,
          '养': 2,
          '。': 8,
          '丘': 1,
          '处': 1,
          '机': 1,
          '、': 1,
          '郭': 5,
          '啸': 3,
          '天': 5,
          '结': 1,
          '识': 1,
          '后': 1,
          '以': 1,
          '勿': 1,
          '忘': 1,
          '“': 1,
          '靖': 3,
          '耻': 1,
          '”': 1,
          '替': 1,
          '儿': 1,
          '取': 1,
          '名': 1,
          '因': 3,
          '为': 1,
          '贪': 1,
          '图': 1,
          '妻': 2,
          '美': 1,
          '色': 1,
          '杀': 1,
          '害': 2,
          '了': 1,
          '父': 4,
        

In [26]:
# 构建词袋模型，和上一节实验相同，将字典从 2 开始编号，把 0 和 1 空出来，0 作为填充元素，1 作为不在字典中的字的编号
word2idx = dict((w,i+2) for i,w in enumerate(vocab))
word2idx

{'杨': 2,
 '康': 3,
 '，': 4,
 '铁': 5,
 '心': 6,
 '与': 7,
 '包': 8,
 '惜': 9,
 '弱': 10,
 '之': 11,
 '子': 12,
 '金': 13,
 '国': 14,
 '六': 15,
 '王': 16,
 '爷': 17,
 '完': 18,
 '颜': 19,
 '洪': 20,
 '烈': 21,
 '的': 22,
 '养': 23,
 '。': 24,
 '郭': 25,
 '啸': 26,
 '天': 27,
 '靖': 28,
 '因': 29,
 '妻': 30,
 '害': 31,
 '父': 32,
 '张': 33,
 '一': 34,
 '素': 35,
 '小': 36,
 '过': 37,
 '师': 38,
 '生': 39,
 '情': 40,
 '于': 41,
 '黄': 42,
 '其': 43}

In [27]:
import numpy as np
from keras.preprocessing.sequence import pad_sequences
from keras.utils.np_utils import to_categorical

# 构建输入，即对于样本中每一个字，从词袋模型中找到这个字对应的 idx，出现频率过低的字，并没有出现在词袋模型中，此时将这些字的 idx 取为 1
train_x = [[word2idx.get(w, 1) for w in s] for s in datas]

max_len = 64

# 在输入的左边填充 0
train_x = pad_sequences(train_x, max_len, value=0)
## 填充位置编码
train_pos1 = pad_sequences(pos_list1, max_len, value=0)
train_pos2 = pad_sequences(pos_list2, max_len, value=0)
# one_hot 编码 label
train_y = to_categorical(labels, num_classes=len(relation2idx))

train_x.shape, train_y.shape, train_pos1.shape, train_pos2.shape

((8, 64), (8, 4), (8, 64), (8, 64))

In [28]:
from keras.layers import Input, Embedding, concatenate, Conv1D, GlobalMaxPool1D, Dense, LSTM
from keras.models import Model

# 定义输入层
words = Input(shape=(max_len,),dtype='int32')
position1 = Input(shape=(max_len,),dtype='int32')
position2 = Input(shape=(max_len,),dtype='int32')
#  Embedding 层将输入进行编码
pos_emb1 = Embedding(output_dim=16, input_dim=256)(position1)
pos_emb2 = Embedding(output_dim=16, input_dim=256)(position2)
word_emb = Embedding(output_dim=16, input_dim=256)(words)
# 分别拼接 文本编码与位置1 和文本编码与位置2
concat1 = concatenate([word_emb, pos_emb1])
concat2 = concatenate([word_emb, pos_emb2])
# 卷积池化层
conv1 = Conv1D(filters=128, kernel_size=3)(concat1)
pool1 = GlobalMaxPool1D()(conv1)
conv2 = Conv1D(filters=128, kernel_size=3)(concat2)
pool2 = GlobalMaxPool1D()(conv2)
# 拼接，最后接全连接层，激活函数为 softmax
concat = concatenate([pool1, pool2])
out = Dense(units=len(relation2idx),activation='softmax')(concat)

model = Model(inputs=[words, position1, position2],outputs=out)
# 编译模型
model.compile(optimizer='ADAM', loss='categorical_crossentropy', metrics=['accuracy'])
model.summary()

__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            (None, 64)           0                                            
__________________________________________________________________________________________________
input_2 (InputLayer)            (None, 64)           0                                            
__________________________________________________________________________________________________
input_3 (InputLayer)            (None, 64)           0                                            
__________________________________________________________________________________________________
embedding_4 (Embedding)         (None, 64, 16)       4096        input_1[0][0]                    
__________________________________________________________________________________________________
embedding_

In [30]:
# 训练 50 次
model.fit([train_x, train_pos1, train_pos2], train_y, batch_size=8, epochs=50)
model.save('model2.h5')

Epoch 1/50
8/8 [==============================] - 0s 1ms/step - loss: 0.3227 - acc: 1.0000
Epoch 2/50
8/8 [==============================] - 0s 1ms/step - loss: 0.3016 - acc: 1.0000
Epoch 3/50
8/8 [==============================] - 0s 1ms/step - loss: 0.2815 - acc: 1.0000
Epoch 4/50
8/8 [==============================] - 0s 873us/step - loss: 0.2624 - acc: 1.0000
Epoch 5/50
8/8 [==============================] - 0s 748us/step - loss: 0.2441 - acc: 1.0000
Epoch 6/50
8/8 [==============================] - 0s 1ms/step - loss: 0.2268 - acc: 1.0000
Epoch 7/50
8/8 [==============================] - 0s 1ms/step - loss: 0.2104 - acc: 1.0000
Epoch 8/50
8/8 [==============================] - 0s 1ms/step - loss: 0.1949 - acc: 1.0000
Epoch 9/50
8/8 [==============================] - 0s 1ms/step - loss: 0.1805 - acc: 1.0000
Epoch 10/50
8/8 [==============================] - 0s 748us/step - loss: 0.1671 - acc: 1.0000
Epoch 11/50
8/8 [==============================] - 0s 749us/step - loss: 0.1546 - a

In [31]:
test_instance = ['张翠山','殷素素','张无忌,武当七侠之一张翠山与天鹰教紫微堂主殷素素之子。']
test_ne1, test_ne2, test_text = test_instance
test_ne1, test_ne2, test_text

('张翠山', '殷素素', '张无忌,武当七侠之一张翠山与天鹰教紫微堂主殷素素之子。')

In [32]:
# 将预测数据转换为向量
pred_x = [word2idx.get(w, 1) for w in test_text]
idx1 = test_text.index(test_ne1)
idx2 = test_text.index(test_ne2)
pos1 = [i-idx1+translation for i in range(len(test_text))]
pos2 = [i-idx2+translation for i in range(len(test_text))]
pred_x = pad_sequences([pred_x], max_len, value=0)
test_pos1 = pad_sequences([pos1], max_len, value=0)
test_pos2 = pad_sequences([pos2], max_len, value=0)
pred_x, test_pos1, test_pos2

(array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0, 33,  1,  1,  1,  1,  1,  1,  1, 11, 34, 33,
          1,  1,  7, 27,  1,  1,  1,  1,  1,  1,  1, 35, 35, 11, 12, 24]]),
 array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
         33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48]]),
 array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
         22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37]]))

In [33]:
# 翻转 relation2idx 字典
idx2relation = dict(zip(relation2idx.values(),relation2idx.keys()))
# 使用模型进行预测
pred = model.predict([pred_x, test_pos1, test_pos2])
# 模型预测最大值的位置作为预测值
output_idx = np.argmax(pred)
# 找到 idx2relation 中实际的标签
output_label = idx2relation[output_idx]
pred, output_idx, output_label

(array([[0.00337194, 0.98889345, 0.00334646, 0.00438816]], dtype=float32),
 1,
 '配偶')